#!/usr/bin/env bash

#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4000M
#SBATCH --time=01:00:00
#SBATCH --job-name=fastqc
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/home/zwang/assembly_coursee/slurm_out/output_fastqc_%j.o
#SBATCH --error=/home/zwang/assembly_coursee/slurm_out/error_fastqc_%j.e
#SBATCH --partition=pall

Data_PATH=/home/zwang/assembly_coursee/participant_4
QC_out=/home/zwang/assembly_coursee/fastqc_out


module load UHTS/Quality_control/fastqc/0.11.9

cd $Data_PATH
for i in *;do
	cd ${i}
	mkdir $QC_out/${i}
	fastqc -o $QC_out/${i} *.gz
	cd ../
done
