#!/usr/bin/env bash

#SBATCH --time=2-00:00:00
#SBATCH --mem=100
#SBATCH --cpus-per-task=8
#SBATCH --job-name=flye
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/data/u*/zwang/assembly/slurm_out/output_03_flye_%j.o
#SBATCH --error=/data/u*/zwang/assembly/slurm_out/error_03_flye_%j.e
#SBATCH --partition=pall


module add UHTS/Aligner/bowtie2/2.3.4.1
module load UHTS/Analysis/samtools/1.10

draft_genome=/data/users/zwang/assembly/assembly/flye
data=/home/zwang/assembly_coursee/participant_4/Illumina
outfile=/data/users/zwang/assembly/assembly/flye/pilon
cd $draft_genome
# comparation
bowtie2-build -f *.fasta --threads 8 z | bowtie2 \
 -x \
   --sensitive-local \
   -p 8 \
   -1 $data*1.fq.gz \
   -2 $data*2.fq.gz | samtools sort \  
   -T $SCRATCH \
  -@ $SLURM_CPUS_PER_TASK \
    -O bam \
aln.sam \    -o last.sorted.bam
samtools index -b -@ 8 last.sorted.bam

java -Xmx45g -jar /mnt/software/UHTS/Analysis/pilon/1.22/bin/pilon-1.22.jar \
    --genome $draft_genome/*fasta\
    --bam last.sorted.bam \
    --outdir $outfile \
    --threads 8
