#!/usr/bin/env bash

#SBATCH --time=2-00:00:00
#SBATCH --mem=100G
#SBATCH --cpus-per-task=8
#SBATCH --job-name=nummer
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/data/users/zwang/assembly/slurm_out/output_04_b_%j.o
#SBATCH --error=/data/users/zwang/assembly/slurm_out/error_04_b_%j.e
#SBATCH --partition=pall
module add UHTS/Analysis/mummer/4.0.0beta1
export PATH=/software/bin:$PATH

# Define paths to directories
WORKDIR=/data/users/zwang/assembly
REFDIR=/data/courses/assembly-annotation-course/references

cd ${WORKDIR}

# canu path
CANU=${WORKDIR}/03_polishing/canu/canu_polished.fasta

# flye path
FLYE=${WORKDIR}/03_polishing/flye/flye_polished.fasta

cd $WORKDIR/compare_assemblies

nucmer --breaklen 1000 -p canup_vs_ref --mincluster 1000 ${REFDIR}/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa $CANU
nucmer --breaklen 1000 -p flyep_vs_ref --mincluster 1000 ${REFDIR}/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa $FLYE
nucmer --breaklen 1000 -p canup_vs_flyep --mincluster 1000 $CANU $FLYE

mummerplot -f -l -t png --large -p refcanu_out -R ${REFDIR}/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa -Q $CANU canup_vs_ref.delta
mummerplot -f -l -t png --large -p refflye_out -R ${REFDIR}/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa -Q $FLYE flyep_vs_ref.delta
mummerplot -f -l -t png --large -p canuflye_out -R $CANU -Q $FLYE canup_vs_flyep.delta
