#!/usr/bin/env bash

#SBATCH --time=8:00:00
#SBATCH --mem=100
#SBATCH --cpus-per-task=8
#SBATCH --job-name=flye
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --partition=pall

#Add the modules
    module add Blast/ncbi-blast/2.10.1+

#Specify directory structure and create them
    course_dir=/data/users/zwang/assembly_course
        quality_dir=${course_dir}/08_Quality
            UniProt_dir=${quality_dir}/UniProt
                blastdb_dir=${UniProt_dir}/blastdb

    mkdir ${UniProt_dir}
    mkdir ${blastdb_dir}

#Specify the assembly to use
    input_dir=${course_dir}/07_prot_annotation/polished.maker.output.renamed/
    assembly=${input_dir}/polished.all.maker.proteins.fasta.renamed.fasta

#Go to folder where the evaluation results will be stored
    cd ${UniProt_dir}

#Align protein against UniProt database
    makeblastdb -in ${course_dir}/CDS_annotation/MAKER/uniprot_viridiplantae_reviewed.fa -dbtype prot -out ${blastdb_dir}/uniprot.db

    blastp -query ${assembly} -db ${blastdb_dir}/uniprot.db -num_threads 30 -outfmt 6 -evalue 1e-10 -out ${UniProt_dir}/blastp.out
