#!/usr/bin/env bash

#SBATCH --time=8:00:00
#SBATCH --mem=100
#SBATCH --cpus-per-task=8
#SBATCH --job-name=flye
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --partition=pall

#Add the modules
    module add UHTS/Analysis/SeqKit/0.13.2

#Specify directory structure and create them
    course_dir=/data/users/zwang/assembly_course
        comp_genomics_dir=${course_dir}/09_comp_genomics
            genespace_dir=${comp_genomics_dir}/genespace

    mkdir ${genespace_dir}

    genespace_image=${course_dir}/scripts/genespace_1.1.4.sif
    genespace_script=${course_dir}/scripts/genespace.R

apptainer exec \
--bind ${course_dir} \
${genespace_image} Rscript ${genespace_script}

mv ${comp_genomics_dir}/dotplots ${genespace_dir}
mv ${comp_genomics_dir}/orthofinder ${genespace_dir}
mv ${comp_genomics_dir}/pangenes ${genespace_dir}
mv ${comp_genomics_dir}/results ${genespace_dir}
mv ${comp_genomics_dir}/riparian ${genespace_dir}
mv ${comp_genomics_dir}/syntenicHits ${genespace_dir}
mv ${comp_genomics_dir}/tmp ${genespace_dir}
