#!/usr/bin/env bash

#SBATCH --time=8:00:00
#SBATCH --mem=100
#SBATCH --cpus-per-task=8
#SBATCH --job-name=flye
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --partition=pall

COURSEDIR=/data/courses/assembly-annotation-course
WORKDIR=/data/users/zwang/assembly/annotation/week1

cd $WORKDIR

#canu
singularity exec \
--bind $COURSEDIR \
--bind $WORKDIR \
$COURSEDIR/containers2/EDTA_v1.9.6.sif \
EDTA.pl \
  --genome  ${WORKDIR}/canu_polished.fasta #The genome FASTA \
  --species others \
  --step all \
  --cds ${WORKDIR}/TAIR10_cds_20110103_representative_gene_model # The coding sequences FASTA \
  --anno 1 #perform whole-genome TE annotation after TE library construction \
  --threads 16   #Number of threads to run this script (default: 4)



#flye
singularity exec \
--bind $COURSEDIR \
--bind $WORKDIR \
$COURSEDIR/containers2/EDTA_v1.9.6.sif \
EDTA.pl \
  --genome  ${WORKDIR}/flye_polished.fasta #The genome FASTA \
  --species others \
  --step all \
  --cds ${WORKDIR}/TAIR10_cds_20110103_representative_gene_model # The coding sequences FASTA \
  --anno 1 #perform whole-genome TE annotation after TE library construction \
  --threads 16   #Number of threads to run this script (default: 4)
